name: Set up PHP environment
description: Set up the PHP environment to perform various actions in subsequent workflows.

inputs:
  cache_version:
    description: Cache version. Gets appended to the cache key and will therefore invalidate the cache if it changes.
    required: true
  github_token:
    description: GitHub OAuth token.
    required: true

runs:
  using: composite

  steps:
    - name: Set up PHP
      uses: shivammathur/setup-php@a4e22b60bbb9c1021113f2860347b0759f66fe5d # v2.30.0
      with:
        php-version: ${{ matrix.php-version }}
        coverage: none
        tools: composer, parallel-lint
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}

    - name: Get Composer cache directory
      id: composer-cache
      shell: bash
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache dependencies
      id: cache-php-dependencies
      uses: actions/cache@ab5e6d0c87105b4c9c2047343972218f562e4319 # v4.0.1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: php-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('composer.lock') }}-${{ inputs.cache_version }}
