name: Node

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main
      - release
  pull_request:
    types:
      - opened
      - ready_for_review
      - synchronize
    # Only run on a given PR if relevant files have changed.
    paths:
      - '**/*.js'
      - '**/*.jsx'
      - '.babelrc.js'
      - '.eslintrc'
      - '.eslintignore'
      - 'package.json'
      - 'package-lock.json'
      - '**/*.yml'

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  node:
    name: Node
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Node
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --progress=false --audit=false --fund=false --legacy-peer-deps

      - name: Lint code
        run: npm run lint:js

      - name: Build application
        run: npm run build
