name: Build to "release-develop" branch

on:
  push:
    branches:
      - ci-modernization

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  release:
    name: "Update release branch"
    uses: humanmade/hm-github-actions/.github/workflows/build-and-release-node.yml@a9a243d6c42fbff4a967d7ce0a6b307bc77251b7 # v0.1.0
    with:
      node_version: 20
      source_branch: ci-modernization
      release_branch: release-develop
      built_asset_paths: build
      build_script: |
        npm ci
        npm run build
